<?php

declare(strict_types=1);

namespace SixtyEightPublishers\AmpClient\Renderer\Phtml;

use SixtyEightPublishers\AmpClient\Renderer\ClientSideMode;
use SixtyEightPublishers\AmpClient\Request\ValueObject\Position;
use SixtyEightPublishers\AmpClient\Request\ValueObject\BannerResource;

/** @var Position $position */
/** @var array<string, scalar|null> $elementAttributes */
/** @var array<string, scalar> $options */
/** @var ClientSideMode $mode */
?>
<div data-amp-banner="<?= Helpers::escapeHtmlAttr($position->getCode()) ?>"
    <?= Helpers::printAttributes(array_merge(
            ['data-amp-mode' => $mode->isEmbed() ? $mode->getValue() : null],
            array_map(static fn (BannerResource $resource): string => implode(',', $resource->getValues()), Helpers::prefixKeys($position->getResources(), 'data-amp-resource-')),
            Helpers::prefixKeys($options, 'data-amp-option-'),
            $elementAttributes
    )) ?>>
</div>
