<?php

declare(strict_types=1);

namespace SixtyEightPublishers\AmpClient\Renderer\Phtml;

use SixtyEightPublishers\AmpClient\Renderer\Options;
use SixtyEightPublishers\AmpClient\Response\ValueObject\Position;
use SixtyEightPublishers\AmpClient\Response\ValueObject\Banner;
use SixtyEightPublishers\AmpClient\Response\ValueObject\NoContent;
use SixtyEightPublishers\AmpClient\Response\ValueObject\HtmlContent;
use SixtyEightPublishers\AmpClient\Response\ValueObject\ImageContent;
use SixtyEightPublishers\AmpClient\Renderer\BreakpointStyle\BreakpointStyle;

/** @var Position $position */
/** @var ?Banner $banner */
/** @var Options $options */

$style = new BreakpointStyle($position, $banner);
?>
<?php foreach ($banner->getContents() as $content) : ?>
    <?php if ($content instanceof ImageContent) : ?>
        <a data-amp-content-breakpoint="<?= Helpers::escapeHtmlAttr($content->getBreakpoint() ?? 'default') ?>"
           data-amp-content-type="img"
           class="amp-banner__content amp-banner__content--img"
           href="<?= Helpers::escapeHtmlAttr($content->getHref()) ?>"
           <?php if (NULL !== $content->getTarget()) : ?>target="<?= Helpers::escapeHtmlAttr($content->getTarget()) ?>"<?php endif ?>>
            <picture>
                <?php if (null !== ($mediaForInvisibleContent = $style->getMediaForInvisibleContent($content->getBreakpoint()))) : ?>
                    <source srcset="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs="
                            media="<?= Helpers::escapeHtmlAttr($mediaForInvisibleContent) ?>">
                <?php endif ?>
                <?php foreach ($content->getSources() as $source) : ?>
                    <source type="<?= Helpers::escapeHtmlAttr($source->getType()) ?>"
                            srcset="<?= Helpers::escapeHtmlAttr($source->getSrcset()) ?>"
                            sizes="<?= Helpers::escapeHtmlAttr($content->getSizes()) ?>">
                <?php endforeach ?>
                <img srcset="<?= Helpers::escapeHtmlAttr($content->getSrcset()) ?>"
                     src="<?= Helpers::escapeHtmlAttr($content->getSrc()) ?>"
                     sizes="<?= Helpers::escapeHtmlAttr($content->getSizes()) ?>"
                     alt="<?= Helpers::escapeHtmlAttr($content->getAlt()) ?>"
                     <?php if (null !== $content->getDimensions()->getWidth()) : ?>width="<?= Helpers::escapeHtmlAttr($content->getDimensions()->getWidth()) ?>"<?php endif ?>
                     <?php if (null !== $content->getDimensions()->getHeight()) : ?>height="<?= Helpers::escapeHtmlAttr($content->getDimensions()->getHeight()) ?>"<?php endif ?>
                     <?php if ('' !== $content->getTitle()) : ?>title="<?= Helpers::escapeHtmlAttr($content->getTitle()) ?>"<?php endif ?>
                     <?php if (null !== ($loading = $options->evaluate('loading', $index ?? 0))) : ?>loading="<?= Helpers::escapeHtmlAttr($loading) ?>"<?php endif ?>
                     <?php if (null !== ($fetchPriority = $options->evaluate('fetchpriority', $index ?? 0))) : ?>fetchpriority="<?= Helpers::escapeHtmlAttr($fetchPriority) ?>"<?php endif ?>>
            </picture>
        </a>
    <?php elseif ($content instanceof HtmlContent) : ?>
        <div data-amp-content-breakpoint="<?= Helpers::escapeHtmlAttr($content->getBreakpoint() ?? 'default') ?>"
             data-amp-content-type="html"
             class="amp-banner__content amp-banner__content--html">
            <?= $content->getHtml() ?>
        </div>
    <?php elseif ($content instanceof NoContent) : ?>
        <div data-amp-content-breakpoint="<?= Helpers::escapeHtmlAttr($content->getBreakpoint() ?? 'default') ?>"
             data-amp-content-type="noContent"
             class="amp-banner__content amp-banner__content--noContent">
        </div>
    <?php endif ?>
<?php endforeach ?>
<?= $style ?>
