<?php

declare(strict_types=1);

namespace SixtyEightPublishers\AmpClient\Renderer\Phtml;

use SixtyEightPublishers\AmpClient\Response\ValueObject\Position;
use SixtyEightPublishers\AmpClient\Renderer\AmpBannerExternalAttribute;

/** @var Position $position */
/** @var array<string, scalar|null> $elementAttributes */
?>
<div data-amp-banner="<?= Helpers::escapeHtmlAttr($position->getCode()) ?>"
     data-amp-banner-external="<?= Helpers::escapeHtmlAttr(AmpBannerExternalAttribute::notFound($position)) ?>"
    <?= Helpers::printAttributes($elementAttributes) ?>>
</div>
