<?php

declare(strict_types=1);

namespace SixtyEightPublishers\AmpClient\Renderer\Phtml;

use SixtyEightPublishers\AmpClient\Response\ValueObject\Position;
use SixtyEightPublishers\AmpClient\Response\ValueObject\Banner;
use SixtyEightPublishers\AmpClient\Renderer\Fingerprint;

/** @var Position $position */
/** @var ?Banner $banner */
?>
<div data-amp-banner="<?= Helpers::escapeHtmlAttr($position->getCode()) ?>" data-amp-attached>
    <?php if (NULL !== $banner && 0 < count($banner->getContents())): ?>
        <div class="amp-banner amp-banner--random"
             data-amp-banner-fingerprint="<?= Helpers::escapeHtmlAttr(Fingerprint::create($position, $banner)) ?>">
            <?php include __DIR__ . '/contents.fragment.phtml' ?>
        </div>
    <?php endif ?>
</div>
