<?php

declare(strict_types=1);

namespace SixtyEightPublishers\AmpClient\Renderer\Phtml;

use SixtyEightPublishers\AmpClient\Response\ValueObject\Position;
use SixtyEightPublishers\AmpClient\Response\ValueObject\Banner;
use SixtyEightPublishers\AmpClient\Renderer\Fingerprint;
use SixtyEightPublishers\AmpClient\Renderer\AmpBannerExternalAttribute;

/** @var Position $position */
/** @var ?Banner $banner */
/** @var array<string, scalar|null> $elementAttributes */
/** @var array<string, scalar> $options */
?>
<div data-amp-banner="<?= Helpers::escapeHtmlAttr($position->getCode()) ?>"
     data-amp-banner-external="<?= Helpers::escapeHtmlAttr(AmpBannerExternalAttribute::rendered($position)) ?>"
    <?= Helpers::printAttributes(array_merge(Helpers::prefixKeys($options, 'data-amp-option-'), $elementAttributes)) ?>>
    <?php if (NULL !== $banner && 0 < count($banner->getContents())): ?>
        <div class="amp-banner amp-banner--random"
             data-amp-banner-fingerprint="<?= Helpers::escapeHtmlAttr(Fingerprint::create($position, $banner)) ?>"
             data-amp-banner-id="<?= Helpers::escapeHtmlAttr($banner->getId()) ?>">
            <?php include __DIR__ . '/contents.fragment.phtml' ?>
        </div>
    <?php endif ?>
</div>
